### PR TITLE
Added method startLoaderWithColor

### PR DESCRIPTION
**Pull request by bguidolim**
- Now you can set a color for your loader;
- Project clean up;
- Podspec fix;

### CODE REVIEW

**Comment by rounak** [comment]
Thanks for the PR. I intentionally kept the Pods directory so that the example project would simply be a built and run.

**Comment by bguidolim** [comment]
So, what is your thoughts about the new feature?

**Comment by rounak** [comment]
I want to merge the startLoaderWithColor addition if that's what you're asking. But didn't want to get rid of the Pods directory.

**Comment by bguidolim** [comment]
No problem, go ahead ;)
Do you want a new pull request with starLoaderWithColor only?

**Comment by rounak** [comment]
That would be awesome

Rounak

**Pull request closed without merging**
