### PR TITLE
Added startLoaderWithColor:

### PR DESCRIPTION
**Pull request by bguidolim**

### CODE REVIEW

**Comment by rounak** [comment]
UIView has a tintColor property already right? We can use that along with `tintColorDidChange`

**Comment by bguidolim** [comment]
You are absolutely right.

**Comment by rounak** [comment]
Another suggestion: In `initWithFrame:` in `RJCircularLoaderView` you can use the tintColor to initialise the strokeColor:

```
_circlePathLayer.strokeColor = self.tintColor.CGColor;
```

Then, there's no need for `startLoaderWithColor:`. Just `startLoader` and to change the color, users of the library can change the `tintColor`, which we can document in the README.

**Comment by bguidolim** [comment]
I don't think so, which color will be default by this way? We don't need to set a color in `initWithFrame:` because `tintColorDidChange` handles it for us.
About `startLoaderWithColor:`, I consider a "nice to have".

**Comment by rounak** [comment]
The default iOS `tintColor` is a shade of dark blue, which works well IMO. Let's do this. Set `strokeColor` to be default `tintColor` in `init`, and then change the methods below a little in this way:

```
- (void)startLoader
{
    RJCircularLoaderView *loaderView = self.rj_circularLoaderView;
    loaderView.frame = self.bounds;
    [self addSubview:loaderView];
    loaderView.progress = 0;
}

- (void)startLoaderWithTintColor:(UIColor *)color
{
    [self startLoader];
    self.rj_circularLoaderView.tintColor = color;
}
```

**Comment by rounak** [comment]
Thanks a lot @bguidolim!

**Comment by bguidolim** [comment]
You're welcome!

Could you create a tag 0.2.0 and update Podspec in the cocoapods specs repo?
I'm using in a project already :)

**Comment by rounak** [comment]
On it!

**Comment by rounak** [comment]
Should be available now

Rounak

**Comment by bguidolim** [comment]
Many thanks ;)

**Pull request merged**
